version: "3.2"

services:
  updater-api:
    build:
      context: updater-api
    environment:
      NATS_URI: nats://nats:4222
    container_name: updater-api
    depends_on:
      - redis
      - nats
      - updater-mankeli

  updater-mankeli:
    build:
      context: updater-api
    environment:
      NATS_URI: nats://nats:4222
    depends_on:
      - redis
      - nats

  redis:
    image: redis:5.0.7
    command: ["redis-server", "--appendonly", "yes"]
    container_name: sis-redis
    volumes:
      - sis-updater-redis:/data

  nats:
    image: nats-streaming:0.16.2
    command: -cid sis-updater-nats --file_slice_max_bytes 0 --file_slice_max_age 100h --max_msgs 10000 -store file -dir datastore
    container_name: sis-nats
    volumes:
      - sis-updater-datastore:/datastore

volumes:
  sis-updater-redis:
  sis-updater-datastore:
