version: "3.2"

services:
  importer-mankeli:
    build:
      context: importer-mankeli
    environment:
      NATS_URI: importer-nats://importer-nats:4222
      DB_PORT: 5432
      DB_HOST: importer-db
      DB_DATABASE: importer-db
    depends_on:
      - importer-db
      - importer-redis
      - importer-nats

  importer-api:
    build:
      context: importer-api
    environment:
      NATS_URI: importer-nats://importer-nats:4222
    container_name: sis-importer-api
    depends_on:
      - importer-mankeli

  importer-db:
    image: postgres:9.6.3
    volumes:
      - sis-importer-pgdata:/var/lib/postgresql/data
    container_name: sis-importer-db

  importer-redis:
    image: redis:5.0.7
    command: ["redis-server", "--appendonly", "yes"]
    container_name: sis-redis
    volumes:
      - sis-importer-redis:/data

  importer-nats:
    image: nats-streaming:0.16.2
    container_name: sis-importer-nats
    volumes:
      - sis-importer-datastore:/datastore

volumes:
  sis-importer-redis:
  sis-importer-datastore:
  sis-importer-pgdata:
