version: "3.2"

services:
  importer-test-db-mankeli:
    build:
      args:
        NODE_ENV: "development"
      context: .
    command: "npm run start:dev"
    depends_on:
      - importer-test-db
    environment:
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_HOST: importer-test-db
      DB_DATABASE: importer-db
    volumes:
      - mankeli_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  importer-test-db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - importer-test-pgdata:/var/lib/postgresql/data
    container_name: importer-test-db

volumes:
  importer-test-pgdata:
  mankeli_modules:
