version: "3.2"

services:
  importer-api:
    build:
      args:
        NODE_ENV: "development"
    env_file:
      - importer-api/.env
    command: "npm run start:dev"
    volumes:
      - ./importer-api:/usr/src/app

  importer-mankeli:
    build:
      args:
        NODE_ENV: "development"
    env_file:
      - importer-mankeli/.env
    environment:
      DB_USERNAME: dev
      DB_PASSWORD: dev
    command: "npm run start:dev"
    volumes:
      - ./importer-mankeli:/usr/src/app

  importer-db:
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: importer-db
