version: "3.2"

services:
  importer-api:
    build:
      args:
        NODE_ENV: "development"
    env_file:
      - importer-api/.env
    command: "npm run start:dev"
    volumes:
      - ./importer-api:/usr/src/app

  importer-mankeli:
    build:
      args:
        NODE_ENV: "development"
    env_file:
      - importer-api/.env
    command: "npm run start:dev"
    volumes:
      - ./importer-mankeli:/usr/src/app

