name: importer-mankeli

on:
  push:
    branches:
      - master
      - trunk 
    paths:
      - importer-mankeli/**
      - .github/workflows/importer-mankeli.yml

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: npm ci --prefix ./importer-mankeli
      
    - name: Test
      run: npm test --prefix ./importer-mankeli

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-mankeli
        path: importer-mankeli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true

  notify:
    runs-on: ubuntu-20.04
    needs: [build-test-push]
    if: always()
    steps:
      - name: Notify failed
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.build-test-push.result != 'success')
        with:
          webhook-url: ${{ secrets.SLACKBOT_URL }}
          message-type: test-failure
      - name: Notify success
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.build-test-push.result != 'success')
        with:
          webhook-url: ${{ secrets.SLACKBOT_URL }}
          message-type: deployment
          deployment-target: production
          softa-url: https://youtu.be/0Bmhjf0rKe8
