name: importer-api

on:
  push:
    branches:
      - master
      - trunk 
    paths:
      - importer-api/**
      - .github/workflows/importer-api.yml

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm test --prefix ./importer-api
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-api
        path: importer-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true       
