name: importer-api

on:
  push:
    branches:
      - master
      - trunk 
    paths:
      - importer-api/**
      - .github/workflows/importer-api.yml

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: npm ci --prefix ./importer-api
      
    - name: Test
      run: npm test --prefix ./importer-api
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-api
        path: importer-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true       

  notify:
    runs-on: ubuntu-20.04
    needs: [build-test-push]
    if: always()
    steps:
      - name: Notify failed
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.build-test-push.result != 'success')
        with:
          webhook-url: ${{ secrets.SLACKBOT_URL }}
          message-type: test-failure
      - name: Notify success
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.build-test-push.result != 'success')
        with:
          webhook-url: ${{ secrets.SLACKBOT_URL }}
          message-type: deployment
          deployment-target: production
          softa-url: https://youtu.be/C_S5cXbXe-4
