name: importer-api

on:
  push:
    branches:
      - trunk
    paths:
      - importer-api/**
      - .github/workflows/importer-api-staging.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/run-tests
        with:
          path: importer-api

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/build-and-push-image
        with:
          tag: staging
          password: ${{ secrets.QUAY_IO_TOKEN }}
