name: importer-mankeli

on:
  push:
    branches:
      - master
      - trunk 
    paths:
      - importer-mankeli/**

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: npm test --prefix ./importer-mankeli

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-mankeli
        path: importer-mankeli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
