name: importer-db-api

on:
  push:
    branches:
      - master
      - trunk 
    paths:
      - importer-db-api/**
      - .github/workflows/importer-db-api.yml

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to toska docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.toska.cs.helsinki.fi
          username: ${{ secrets.TOSKAREGISTRY_USERNAME }}
          password: ${{ secrets.TOSKAREGISTRY_PASSWORD }}

      - name: Lint and test
        run: npm run ci --prefix ./importer-db-api

  build-push:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        repository: toska/sis-importer-db-api
        path: importer-db-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true

  notify:
    runs-on: ubuntu-20.04
    needs: [test-lint, build-push]
    if: always()
    steps:
      - name: Notify failed
        if: (needs.test-lint.result != 'success' || needs.build-push.result != 'success')
        env:
          SLACKBOT_URL: ${{ secrets.SLACKBOT_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl --silent -X POST -H 'Content-type: application/json' --data "{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"Test run failed on ${GITHUB_REF##*/} :kurkkumopo:\",\"emoji\":true}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Uh oh, importer-db-api <https://github.com/UniversityOfHelsinkiCS/sis-importer/actions/runs/${GITHUB_RUN_ID}|workflow> run by *$GITHUB_ACTOR* has failed on branch ${GITHUB_REF##*/}. \nCommit: <https://github.com/UniversityOfHelsinkiCS/sis-importer/commit/${GITHUB_SHA}|${GITHUB_SHA:6}>\"}},{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"Commit message: \n $COMMIT_MESSAGE\",\"emoji\":true},\"accessory\":{\"type\":\"image\",\"image_url\":\"https://cataas.com/cat/fail?_=$GITHUB_RUN_ID\",\"alt_text\":\"cat failing\"}}]}" "$SLACKBOT_URL" && exit 1
      - name: Notify success
        if: (needs.test-lint.result == 'success' || needs.build-push.result == 'success')
        env:
          SLACKBOT_URL: ${{ secrets.SLACKBOT_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl --silent -X POST -H 'Content-type: application/json' --data "{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"Importer-db-api ${GITHUB_REF##*/} deploying :rocket:\",\"emoji\":true}},{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"Importer-db-api ${GITHUB_REF##*/} started deployment by $GITHUB_ACTOR.\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Commit <https://github.com/UniversityOfHelsinkiCS/sis-importer/commit/${GITHUB_SHA}|${GITHUB_SHA:6}>: \n$COMMIT_MESSAGE\"},\"accessory\":{\"type\":\"image\",\"image_url\":\"https://cataas.com/cat/?_=$GITHUB_RUN_ID\",\"alt_text\":\"cat\"}}]}" "$SLACKBOT_URL"
